# Generated by Django 5.2.8 on 2025-12-14 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HelpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Информация о помощи',
                'verbose_name_plural': 'Информация о помощи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('payment_type', models.CharField(choices=[('bank', 'Банковский перевод'), ('card', 'Банковская карта'), ('sbp', 'СБП'), ('wallet', 'Электронный кошелек')], max_length=20, verbose_name='Тип платежа')),
                ('recipient_name', models.CharField(blank=True, max_length=300, verbose_name='Получатель')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Расчетный счет')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('payment_purpose', models.CharField(blank=True, max_length=300, verbose_name='Назначение платежа')),
                ('card_number', models.CharField(blank=True, max_length=50, verbose_name='Номер карты/кошелька')),
                ('card_holder', models.CharField(blank=True, max_length=200, verbose_name='Держатель карты')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст (месяцы)')),
                ('photo', models.ImageField(upload_to='pets/', verbose_name='Фотография')),
                ('history', models.TextField(verbose_name='История питомца')),
                ('character', models.TextField(verbose_name='Характер')),
                ('special_needs', models.TextField(blank=True, verbose_name='Особенности')),
                ('is_adopted', models.BooleanField(default=False, verbose_name='Усыновлен')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип питомца')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип питомца',
                'verbose_name_plural': 'Типы питомцев',
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название приюта')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('description', models.TextField(verbose_name='Описание приюта')),
            ],
            options={
                'verbose_name': 'Приют',
                'verbose_name_plural': 'Приюты',
            },
        ),
        migrations.CreateModel(
            name='HappyStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок истории')),
                ('story', models.TextField(verbose_name='История')),
                ('new_owner_name', models.CharField(max_length=100, verbose_name='Имя нового хозяина')),
                ('adoption_date', models.DateField(verbose_name='Дата усыновления')),
                ('photo_after', models.ImageField(upload_to='happy_stories/', verbose_name='Фото в новом доме')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Счастливая история',
                'verbose_name_plural': 'Счастливые истории',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='game.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PetComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pets', models.ManyToManyField(to='game.pet', verbose_name='Питомцы для сравнения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сравнение питомцев',
                'verbose_name_plural': 'Сравнения питомцев',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pettype', verbose_name='Тип питомца'),
        ),
        migrations.AddField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.shelter', verbose_name='Приют'),
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_type', models.CharField(choices=[('food', 'Корм'), ('medical', 'Лечение'), ('toys', 'Игрушки'), ('general', 'Общая поддержка')], max_length=20, verbose_name='Тип помощи')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение питомцу')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pet', verbose_name='Питомец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Спонсор')),
            ],
            options={
                'verbose_name': 'Спонсорство',
                'verbose_name_plural': 'Спонсорство',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'unique_together': {('user', 'pet')},
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес проживания')),
                ('housing_type', models.CharField(max_length=100, verbose_name='Тип жилья')),
                ('has_yard', models.BooleanField(default=False, verbose_name='Есть двор/сад')),
                ('other_pets', models.TextField(blank=True, verbose_name='Другие питомцы')),
                ('experience', models.TextField(verbose_name='Опыт содержания животных')),
                ('motivation', models.TextField(verbose_name='Почему хотите взять этого питомца')),
                ('work_schedule', models.CharField(max_length=200, verbose_name='График работы')),
                ('family_members', models.TextField(verbose_name='Состав семьи')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='game.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Заявка на усыновление',
                'verbose_name_plural': 'Заявки на усыновление',
                'ordering': ['-date_created'],
                'unique_together': {('pet', 'user')},
            },
        ),
    ]
